packages:
  - name: sample
    environment:
      DATABASE: "${DATABASE}"
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
      HOST: "${HOST}"
      PORT: "${PORT}"
    shared: false
    parameters: {}
    annotations: {}
    functions:
      - name: testfunc
        binary: false
        main: ""
        runtime: "python:3.9"
        web: raw
        parameters: {}
        annotations: {}
        limits:
          timeout: 12000
          memory: 1024
